
rollout roll_aPropos "A propos" width:162 height:37
(
	label 'lbl_axeP' "Urba | V0.3.1 | ©" pos:[4,0] width:85 height:13 align:#left
	HyperLink 'hpl1' "Christophe Pagès" pos:[91,1] width:84 height:15 address:"http://c-pages.fr" color:(color 200 200 127.5) hovercolor:(color 250 250 150) visitedcolor:(color 200 200 127.5) align:#left
	HyperLink 'hpl2' "GitHub" pos:[143,14] width:32 height:15 address:"https://github.com/c-pages/cp-Urba-Cleanage" color:(color 200 200 127.5) hovercolor:(color 250 250 150) visitedcolor:(color 200 200 127.5) align:#left
	label 'lbl6' "2018" pos:[4,13] width:24 height:13 align:#left
)
