-- filein "recherche - simpleObject - 02.ms"
(
	clearlistener ()
	-- 	filein "$userScripts\\cp-Urba\\docs\\recherche Bat version mesh (simpleObject)\\facade - sequence.ms"
-- 	include "$userScripts\\cp-Urba\\docs\\recherche Bat version mesh (simpleObject)\\Menuiseries\\Menuiserie - Ensemble.ms"
-- 	filein "$userScripts\\cp-Urba\\docs\\recherche Bat version mesh (simpleObject)\\Menuiseries\\Menuiserie - Ensemble.ms"
	filein "$userScripts\\cp-Urba\\docs\\recherche Bat version mesh (simpleObject)\\recherche - simpleObject - Batiment.ms"
	
	-- 	filein "$userScripts\\cp-Urba\\docs\\recherche Bat version mesh (simpleObject)\\objets simples\\boite.ms"
)