
filein "$userScripts\\cp-Urba\\Batiment (simpleObj)\\Primitives\\Batiment - Primitive - Plan vertical.ms"
filein "$userScripts\\cp-Urba\\Batiment (simpleObj)\\Primitives\\Batiment - Primitive - Plan horizontal.ms"
filein "$userScripts\\cp-Urba\\Batiment (simpleObj)\\Primitives\\Batiment - Primitive - Boite.ms"
filein "$userScripts\\cp-Urba\\Batiment (simpleObj)\\Primitives\\Batiment - Primitive - Boite U.ms"
filein "$userScripts\\cp-Urba\\Batiment (simpleObj)\\Primitives\\Batiment - Primitive - Boite L.ms"
	
	

